
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;


public class courses extends javax.swing.JFrame {
String category;
        public courses(String name) {
        initComponents();
        setSize(600,500);
        
        category=name;
        
        JOptionPane.showMessageDialog(rootPane, category);
        
        load_courses();
        }
        
        void load_courses()
        {
            String ans= myClient.courses(category);
            
            StringTokenizer st=new StringTokenizer(ans,";;");
            
            //get number of rows
            int n= st.countTokens();
            
            JButton arr[]= new JButton[n];
            
            int x=10,y=10;
            for(int i=0;i<n;i++)
            {
                //to get row
                String row=st.nextToken();
                
                //parse particular row
                StringTokenizer st1= new StringTokenizer(row,"$");
                
                //get data from particular row
                int id=Integer.parseInt(st1.nextToken());
                String name= st1.nextToken();
                String photo= st1.nextToken();
                
                arr[i]= new JButton (name);
                
                // create ImageIcon
                
                ImageIcon ic =new ImageIcon (photo);
                
                //resize your image icon using image class 
                
                Image img = ic.getImage().getScaledInstance(100,100,Image.SCALE_SMOOTH);
                
                //convert Image object to ImageIcon 
                
                ImageIcon ic1= new ImageIcon (img);
                
                // set icon on button 
                arr[i].setIcon(ic1);
                
                arr[i].addActionListener(new ActionListener()
                {
                   @Override
                   public void actionPerformed(ActionEvent e)
                   {
                       Lectures obj = new Lectures (id);
                       obj.setVisible(true);
                       dispose();
                   }
                });
                    // set bounds 
                
                arr[i].setBounds(x,y, 200,100);
                
            
                mainpanel.add(arr[i]);
                mainpanel.repaint();
                
                if(x<220)
                {
                    x=x+210;
                    System.out.println("-->"+x);
                }
                else
                {
                    x=10;
                    y=y+110;
                }
                
            }
            mainpanel.setPreferredSize(new Dimension (440,y+100));
        }
                
                    
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(mainpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(28, 67, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courses("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
