
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


public class Manage_Categories extends javax.swing.JFrame {

  File ph;
  JFileChooser jfc;
  
  ArrayList<Category> al=  new ArrayList<>();
  
  myTableModel tm;
    public Manage_Categories() {
        initComponents();
        setSize(800,400);
        
        load_category();
        
        tm= new myTableModel();
        
        mytable.setModel(tm);
    }
    void load_category()
    {
        al.clear();
        String ans= myClient.fetchCat();
        
        StringTokenizer st= new StringTokenizer(ans, ";;");
        
        while(st.hasMoreTokens())
        {
                String row= st.nextToken();
                
                StringTokenizer st1= new StringTokenizer(row,"$");
                
                String name= st1.nextToken();
                String photo= st1.nextToken();
                
                al.add(new Category(name,photo));
        }
        
    }
class myTableModel extends AbstractTableModel
{

        @Override
        public int getRowCount()
        {
          return al.size(); 
        }

        @Override
        public int getColumnCount() 
        {
            return 2;
        }

        @Override
        public Object getValueAt(int i, int j)
        {
           if(j==0)
           {
               return al.get(i).name;
           }
           else
           {
           return al.get(i).photo;
           }
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        catname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Categories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, 2, 800, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 30, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("View Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 20, 110, 30);

        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mytable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 60, 350, 300);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 370, 72, 23);

        jLabel4.setText("Category Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 60, 120, 20);
        getContentPane().add(catname);
        catname.setBounds(30, 90, 310, 22);

        jLabel5.setText("Photo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 80, 16);
        getContentPane().add(photolb);
        photolb.setBounds(30, 170, 210, 160);

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        getContentPane().add(browse);
        browse.setBounds(310, 230, 72, 23);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 280, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        jfc= new JFileChooser();
        
        int ans= jfc.showOpenDialog(this);
        
        if(ans== JFileChooser.APPROVE_OPTION)
        {
            ph=jfc.getSelectedFile();
            
            ImageIcon ic= new ImageIcon(ph.getPath());
            
            Image img= ic.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
            
            ImageIcon ic1 = new ImageIcon (img);
            
            photolb.setIcon(ic1);
        }
    }//GEN-LAST:event_browseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //method
        String category= catname.getText();
        String ans= myClient.addCategory(category,ph);
        
        if(ans.trim().equals("success"))
        {
            JOptionPane.showMessageDialog(rootPane,"Added Success");
            catname.setText("");
            photolb.setIcon(null);
            load_category();
            tm.fireTableDataChanged();
        }
        else
        {
           JOptionPane.showMessageDialog(rootPane,ans); 
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = mytable.getSelectedRow();
        
        if(i==-1)
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select Row!"); 
        }
         else
        {
          String ans = myClient.deletecat(al.get(i).name);
         
         if(ans.trim().equals("success"))
         {
             JOptionPane.showMessageDialog(rootPane, "deleted Successfully");
             load_category();
             tm.fireTableDataChanged();
         }
         else
         {
              JOptionPane.showMessageDialog(rootPane, "Failed");
         }
                
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JTextField catname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mytable;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
